#! /bin/sh

# single monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# for spiral mode
#bspc config automatic_scheme spiral

# for longest side mode
#bspc config automatic_scheme longest_side

# remove X shaped cursor
xsetroot -cursor_name left_ptr

# disable DPMS
xset s off -dpms 

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
dunst &
feh --bg-fill ~/Pictures/archlinux_wallpapers/best_quality.png &
picom & 
easyeffects --gapplication-service &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &

# main settings
bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 	     false
bspc config focus_follows_pointer true

#window rules
bspc rule -a firefox desktop='^1' 
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a Thunderbird desktop='^8'
bspc rule -a Screenkey manage=off
bspc rule -a Galculator state=floating
bspc rule -a Pcsx2 state=floating

#color theme
bspc config focused_border_color "#C2AF8D"
bspc config normal_border_color "#282A2E"
bspc config presel_feedback_color "#74A096"

