#! /bin/sh

# single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9

# remove X shaped cursor
xsetroot -cursor_name left_ptr

# disable DPMS
xset s off -dpms

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
dunst &
$HOME/.fehbg &
picom --experimental-backends & 
easyeffects --gapplication-service &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &

# main settings
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 	     true
bspc config focus_follows_pointer true

# window rules
bspc rule -a firefox desktop='^1' 
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a Thunderbird desktop='^5'
bspc rule -a Galculator state=floating
bspc rule -a Pcsx2 state=floating

# color theme
bspc config focused_border_color "#AF3A03"
bspc config normal_border_color "#504945"
bspc config presel_feedback_color "#F0C674"

